# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: [test, mypy, beautify]
    if: github.repository == 'relekang/python-semantic-release'

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ needs.beautify.outputs.new_sha }}
    - name: Fetch master
      run: git fetch --prune origin +refs/heads/master:refs/remotes/origin/master
    - name: Python Semantic Release
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_username: ${{ secrets.PYPI_USERNAME }}
        pypi_password: ${{ secrets.PYPI_PASSWORD }}
